### ISSUE TITLE
Blocked in running a node app with firewall

### ISSUE THREAD

**Issue by SaurabhhB** [AikidoSec/firewall-node#272]
After installing dependancies and adding the first line of `require('@aikidosec/firewall');` and then running `node server.js` in my node application, the app does not run due to an error in the FW code. The error is as follows:
```
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'node:async_hooks'
Require stack:
- /home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/agent/context/ContextStorage.js
- /home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/agent/Context.js
- /home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/sinks/ChildProcess.js
- /home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/agent/protect.js
- /home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/index.js
- /home/saurabh/NodeGoat/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/agent/context/ContextStorage.js:4:28)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/agent/context/ContextStorage.js',
    '/home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/agent/Context.js',
    '/home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/sinks/ChildProcess.js',
    '/home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/agent/protect.js',
    '/home/saurabh/NodeGoat/node_modules/@aikidosec/firewall/index.js',
    '/home/saurabh/NodeGoat/server.js'
  ]
}
```
![image](https://github.com/AikidoSec/firewall-node/assets/24986354/8e787908-65fb-4bcf-8052-94b3f3f8674b)

The `package.json` as the dependancy of FW as `"@aikidosec/firewall": "1.5.47"`

PS: I an trying to run NodeGoat using Aikido firewall.

**Comment by hansott** [comment]
Hi @SaurabhhB, which node version are you using?

**Comment by SaurabhhB** [comment]
I am using node 12 since the DVWA (NodeGoat) supports that version only.

**Comment by hansott** [comment]
You can use node:16-alpine in the Dockerfile. Just tested it out.

**Comment by SaurabhhB** [comment]
Sounds good. Will try.
